# Generated by Django 5.2.7 on 2025-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_camera_default_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='hand_touch_distance',
            field=models.IntegerField(default=100),
        ),
    ]
